### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by finnhodgkin** [facn2/Alpha.HAML#44]
![brokenlink](https://user-images.githubusercontent.com/22300773/28658154-a03658b8-72b2-11e7-85fc-282c559b82c7.gif)

Leads to nothing...

**Comment by finnhodgkin** [comment]
Oh I see it just takes you to the readme on github pages. That's not really 'checking out' the app.

**Comment by Heathercoraje** [comment]
fixed

**Comment by Heathercoraje** [comment]
fixed. 
Please have a look and close it

**Comment by finnhodgkin** [comment]
:+1:
